In [1]:
import numpy as np

data = np.arange(15)

In [2]:
# 按行reshape
data.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
# 按列reshape
data.reshape(3, 5, order='F')

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [4]:
t = data.reshape(3, 5)

In [5]:
# 每一维度的size
t.shape

(3, 5)

In [6]:
# 维度
t.ndim

2

In [7]:
# 元素数据类型
t.dtype.name

'int64'

In [8]:
# 保存数据的实际内存空间
t.data

In [9]:
type(t)

numpy.ndarray

In [10]:
# create ndarray
a = np.array([1,2,3,4])
b = np.array([(1,2,3),(4,5)])
c = np.array([[1,2,3],[4,5]])
d = np.array([12,3], dtype=np.int64)
d

/Users/xingguan.wzt/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/xingguan.wzt/.pyenv/versions/3.7.3/lib/python3.7/site-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  after removing the cwd from sys.path.


array([12,  3])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [13]:
np.empty((1,3))

array([[7.74860419e-304, 7.74860419e-304, 7.74860419e-304]])

In [14]:
np.arange(10, 30, 5) # sequence of array [10, 30) step=5

array([10, 15, 20, 25])

In [15]:
np.linspace(0, 10, 8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [16]:
np.arange(24).reshape(2,4,3) # np.arange(24).reshape(2,4,4) error

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [17]:
a = np.array([20,21,22,23])
b = np.arange(4)

In [18]:
a + 1

array([21, 22, 23, 24])

In [19]:
a + b

array([20, 22, 24, 26])

In [20]:
a * b

array([ 0, 21, 44, 69])

In [21]:
b ** 2

array([0, 1, 4, 9])

In [22]:
a + np.sin(b)

array([20.        , 21.84147098, 22.90929743, 23.14112001])

In [23]:
a < 10

array([False, False, False, False])

In [24]:
a < 22

array([ True,  True, False, False])

In [25]:
a = np.array([[1,1],[0,4]])
b = np.array([[2,1],[1,3]])

In [26]:
a * b # elementwise product

array([[ 2,  1],
       [ 0, 12]])

In [27]:
a @ b # matrix product

array([[ 3,  4],
       [ 4, 12]])

In [28]:
a.dot(b) # another matrix product

array([[ 3,  4],
       [ 4, 12]])

In [29]:
import sys
sys.path

['/Users/xingguan.wzt/github.com/wzt3309/tutorials/python-sci',
 '/Users/xingguan.wzt/.pyenv/versions/3.7.3/lib/python37.zip',
 '/Users/xingguan.wzt/.pyenv/versions/3.7.3/lib/python3.7',
 '/Users/xingguan.wzt/.pyenv/versions/3.7.3/lib/python3.7/lib-dynload',
 '',
 '/Users/xingguan.wzt/.pyenv/versions/3.7.3/lib/python3.7/site-packages',
 '/Users/xingguan.wzt/.pyenv/versions/3.7.3/lib/python3.7/site-packages/IPython/extensions',
 '/Users/xingguan.wzt/.ipython']

In [30]:
np.__file__

'/Users/xingguan.wzt/.pyenv/versions/3.7.3/lib/python3.7/site-packages/numpy/__init__.py'

In [31]:
a = np.linspace(0, np.pi, 3)

In [32]:
a.sum()

4.71238898038469

In [33]:
a.max()

3.141592653589793

In [34]:
a = np.arange(15).reshape(3,5)

In [35]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
a.sum(axis=0) # column sum

array([15, 18, 21, 24, 27])

In [37]:
a.sum(axis=1) # row sum

array([10, 35, 60])

In [38]:
a = np.arange(8).reshape(2,2,2)

In [39]:
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
a.sum(axis=0)

array([[ 4,  6],
       [ 8, 10]])

In [41]:
a.sum(axis=1)

array([[ 2,  4],
       [10, 12]])

In [43]:
a.sum(axis=2)

array([[ 1,  5],
       [ 9, 13]])